#+TITLE: IIR Hardware Notebook

* Wednesday, 1/11/17
	Start: 2:00PM

	I started actually creating the VHDL file. I started by just placing the
	things that I believed needed to be there. The entity and architecture were
	built kinda.

	End: 5:00PM

	Start: 7:45PM

	I found a [[https://github.com/tgingold/ghdl][program]] that will simulate VHDL. My entire design is screwed up!

	I basically worked out most of the kinks /except/ the arrays aren't happy.

	End: 8:50 PM

* Thursday, 1/12/17
	Start: 7:45PM

	Attempting to fix these arrays...

	I fixed the arrays... They're even worse than I thought! Damn you VHDL... Damn
	you.

	Anyways, I'm ready to test my FIR design. Vivado! Oh Vivado, where art thou
	Vivado!?

	*IMPORTANT NOTE: GHDL seems to think certain pieces of "code" are incorrect*
  *when they seem perfectly fine. As of now, I'm assuming GHDL is making*
  *mistakes and will test it out in Vivado someday.*

	End: 8:37PM
* Friday, 1/13/17
	Start: 3:00PM

	I began working with Vivado to hopefully see if my FIR was working.

	Problem: I had many issues that were present. Such was declaring variables in
	the wrong part of the design. They /must/ go in a process /before/ the `begin'
	statement. Also, I had an issue with Vivado in general. I couldn't get the ILA
	working very well.

	I've decided to just go in and try it with actual voltages.

	Issues: There are a handful of issues that I will need to take care of before
	I can even do anything with the XADC.
	- I will need a GPIO to output the correct channel to the IP.
	- I need to get the IP to actually build.
	- Pain and suffering.

  End: 5:16PM
